export { default as CardImage } from "./card-1-image.png";
export { default as CardImage2 } from "./card-2-image.jpg";
export { default as CardImage3 } from "./card-3-image.jpg";
export { default as MeetandGreet } from "./meet-and-greet.avif";
export { default as PeopleNetworking } from "./create-connection.avif";
export { default as tn } from "./tnl-logo.png";
export { default as edinburgh } from "./edinburgh.png";
export { default as WhatWeDoImage } from "./what-we-do-image.jpeg"
export { default as OurCommunityImage } from "./our-community-image.jpg"
export { default as MentorshipSchemeImage } from "./mentorship-scheme-image.jpg"
export { default as UniqueEventsImage } from "./unique-events-image.jpg"
export { default as OurVisionImage } from "./our-vision-image.png"
export { default as OurMissionImage } from "./our-mission-image.jpg"
export { default as OurValuesImage } from "./our-values-image.jpg"
export { default as CuriousImage } from "./curious-image.jpg"
export { default as Caitlin } from "./caitlin.jpg"
export { default as Eva } from "./eva.jpg"
export { default as Inga } from "./inga-dale.jpg"
export { default as Ola } from "./ola.jpeg"
export { default as Vicky } from "./vicky.jpeg"
export { default as Zoe } from "./zoe-alba.jpg"
// export { default as  } from "./"
